spring.application.name: gateway
server.port: 8081

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway

spring:
  security.oauth2:
    client:
      provider.tanie-balony-keycloak:
        issuer-uri: "http://localhost:8080/realms/TanieBalony"
      registration.tanie-balony-keycloak:
        provider: tanie-balony-keycloak
        authorization-grant-type: authorization_code
        client-id: gateway
        client-secret: ecfHeiInmTNGkDVIxWly8yXNQclUGnwU
        scope: openid,profile,email
  cloud:
    gateway:
      routes:
        - id: apiTest
          uri: http://localhost:8082
          predicates:
            - Path=/api/**
#          filters:
#            - AuthFilter
        - id: api
          uri: http://localhost:8082
          predicates:
            - Path=/**
#          filters:
#            - AuthFilter
