spring.application.name: gateway
server.port: 8081

spring:
  security.oauth2:
    client:
      provider.tanie-balony-keycloak.issuer-uri: "http://localhost:8080/realms/TanieBalony"
      registration.keycloak:
        provider: tanie-balony-keycloak
        authorization-grant-type: authorization_code
        client-id: gateway
        client-secret: password
        scope: openid
  cloud:
    gateway:
      routes:
        - id: apiTest
          uri: http://localhost:8082
          predicates:
            - Path=/api/**
          filters:
            - AuthFilter
        - id: api
          uri: http://localhost:8088
          predicates:
            - Path=/**
          filters:
            - AuthFilter
