services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    ports:
      - "8080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/awasome
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=admin
      - KC_FILE=/opy/keycloak/conf/Users-realm.json
    volumes:
      - ./contrib/example-config:/opt/keycloak/conf
    depends_on:
      - db
    command: "start-dev --health-enabled=true"
    networks:
      - inner_network

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: awasome
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - inner_network

  keycloak-config-cli:
    image: adorsys/keycloak-config-cli:latest
    depends_on:
      - keycloak
    volumes:
      - ./contrib/example-config:/config
    environment:
      - KEYCLOAK_URL="http://172.22.0.1:8080"
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - EYCLOAK_AVAILABILITYCHECK_ENABLED
      - SPRING_PROFILES_ACTIVE
      - DEBUG
    networks:
      - inner_network
volumes:
  db-data:

networks:
  inner_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16