version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    ports:
      - "8080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/awasome
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=admin
    depends_on:
      - db
    command: start-dev

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: awasome
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db-data:/var/lib/postgresql/data

  keycloak-config-cli:
    build: .
    image: adorsys/keycloak-config-cli:latest
    depends_on:
      - keycloak
    volumes:
      - ./contrib/example-config:/config
    environment:
      - keycloak.url=http://keycloak:8080
      - keycloak.user=admin
      - keycloak.password=admin123
      - keycloak.availability-check.enabled=true
      - spring.profiles.active=dev
      - import.cache.enabled=false

volumes:
  db-data:
