version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    ports:
      - "8080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/awasome
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=admin
    depends_on:
      - db
    command: start-dev

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: awasome
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
